apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-lens-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary-lens-service
  template:
    metadata:
      labels:
        app: summary-lens-service
    spec:
      containers:
      - name: summary-lens-service
        image: gravitate-registry.cr.de-fra.ionos.com/summary-lens-service:v0.5.0
        imagePullPolicy: Always
        env:
        - name: SERVER_URL
          value: "https://fosps.gravitatehealth.eu/"
        - name: MODEL_URL
          value: "https://ollama.lst.tfo.upm.es"
        - name: OPENAI_KEY
          value: ""
        - name: GROQ_API_KEY
          value: ""
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
status: {}
